### PR TITLE
Keep reference of copied items for cross referencing

### PR DESCRIPTION
**Pull request by saschahofmann**
As explained in https://github.com/tj-django/django-clone/issues/544, I am trying to keep track of instances that have been cloned before and reuse that copy for later references that otherwise would be cloned again.

I added on example test, are you ok with me adding cross-references between the tables or should I create new models and do you prefer one big test for all cases or individual ones?

### CODE REVIEW

**Comment by saschahofmann** [comment]
@jackton1 Closed the other in favor of this. I fixed the linting errors and added another assert in the test. Ready for review IMO.

**Comment by saschahofmann** [comment]
Ok. Nvm there is an issue with the o2o cloning. Will fix and test

**Comment by saschahofmann** [comment]
Ok the issue only appears if I make `__duplicate_o2m_fields` call make_clone which I want to add as well. I'll do it here as well. I hoped to separate them but I think it makes sense to do them together

**Comment by jackton1** [comment]
> Hello @saschahofmann! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
> * In the file [`model_clone/mixin.py`](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py):
> 
> > [Line 230:101](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L230): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (109 > 100 characters)
> > [Line 299:101](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L299): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (109 > 100 characters)
> > [Line 314:26](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L314): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> > [Line 469:23](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L469): [E271](https://duckduckgo.com/?q=pep8%20E271) multiple spaces after keyword
> > [Line 472:101](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L472): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (139 > 100 characters)
> > [Line 475:25](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L475): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> > [Line 476:25](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L476): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> > [Line 477:25](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L477): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> > [Line 478:25](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L478): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> > [Line 479:21](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/mixin.py#L479): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> 
> * In the file [`model_clone/tests/test_clone_mixin.py`](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/tests/test_clone_mixin.py):
> 
> > [Line 887:12](https://github.com/tj-django/django-clone/blob/16bc2b5f57fc16edd037b6035ecd84208cd573a0/model_clone/tests/test_clone_mixin.py#L887): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

@saschahofmann Can you also resolve these errors.

**Comment by saschahofmann** [comment]
Ran black now. hope that did it.

**Comment by saschahofmann** [comment]
Two suggestions:
* I would turn off the code scanner seems like it's just cluttering the diff preview hard to find the codecov prompts among all these useless suggestions
* Maybe we can bump min python dependency to 3.6 or even 3.8?

**Comment by jackton1** [comment]
> Two suggestions:
> 
> * I would turn off the code scanner seems like it's just cluttering the diff preview hard to find the codecov prompts among all these useless suggestions
> * Maybe we can bump min python dependency to 3.6 or even 3.8?

Seems we need to improve the test coverage it’s currently under 100%

**Comment by saschahofmann** [comment]
Yeah exactly and it's super annoying to find which lines are covered because half the file is flagged by codescanner

**Comment by saschahofmann** [comment]
@jackton1 I actually discovered a few problems with cross-references. I think it boils down to this: `_create_copy_of_instance` creates and copies one_to_onefields before make_clone can replace the objects. 

Example:
```python

class Sentence(CloneMixin, models.Model):
    value = models.TextField()

    _clone_o2o_fields = {"ending",}


class Ending(CloneMixin, models.Model):
    sentence = models.OneToOneField(
        Sentence, on_delete=models.CASCADE, related_name="ending"
    )
    _clone_o2o_fields = {"sentence"}


class Triangle(CloneMixin, models.Model):
    sentence = models.OneToOneField(
        Sentence, on_delete=models.CASCADE, related_name="triangle"
    )
    ending = models.OneToOneField(
        Ending, on_delete=models.CASCADE, related_name="triangle"
    )

    _clone_o2o_fields = {"sentence", "ending"}
    ```

This is a triangular relationship
```
            Triangle
           /            \
         v              v
   Sentence <- Ending
```
When it copies `ending` it will call `_create_copy_of_instance` and that will `_create_copy_of_instance` for `sentence` 
but this time with sub_clone=True which leads to an IntegrityError because it tries to keep the sentence_id. I think this error should only happen if one of these models wasn't a CloneMixin or maybe not even then. Anyway, is there a way we can set the one_to_one fields of the duplicate to null and replace them in the actual make_clone command?

**Comment by jackton1** [comment]
@saschahofmann See: #669

**Pull request closed without merging**
